KapiBara/controller_manager:
  ros__parameters:
    use_sim_time: true

    imu_sensor_broadcaster:
        type: imu_sensor_broadcaster/ImuSensorBroadcaster

imu_sensor_broadcaster:
  ros__parameters:
    sensor_name: "kapibara_imu" # Must match URDF <sensor name="...">
    frame_id: "kapibara_imu_link" # The TF frame it will publish data to